version: '3.8'

services:
  centrifugo:
    image: centrifugo/centrifugo:v6
    command:
      - centrifugo
      - --config=/centrifugo_test.json
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo_test.json:/centrifugo_test.json:ro
