#!/usr/bin/env bash
wget https://raw.githubusercontent.com/centrifugal/centrifuge/master/misc/proto/client.proto -O /tmp/client.proto
./node_modules/.bin/pbjs -t json /tmp/client.proto > ./src/client.proto.json
