#!/usr/bin/env bash
wget https://raw.githubusercontent.com/centrifugal/protocol/master/definitions/client.proto -O /tmp/client.proto
./node_modules/.bin/pbjs -t json --keep-case /tmp/client.proto > ./src/client.proto.json
